name: Deploy Website to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IPFS via Pinata
        uses: anoukleyris/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Mon site'
          path: './site' 
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          remove-old: false
